### ISSUE TITLE
Not Working in iPad / iPhone

### ISSUE THREAD

**Issue by cmprogrock** [oblador/angular-parallax#7] opened 2014-04-02 00:49 UTC
Hi,
Your Example does not work in iOS. 
Any plans to update to make it work in iOS?

(Stellar.js has some info about ios issues)
Thx

**Comment by fisshy** [comment] 2014-04-02 05:07
we had this issue up few months ago. 

when you touch and scroll in iOS you lock the execution of JavaScript and only once you release the animations will go off. 

we created a different approach for our mobile version :)

**Comment by oblador** [comment] 2014-04-02 07:23
No plans at this time. Dupe of https://github.com/durated/angular-parallax/issues/3

**Closed as completed by oblador** 2014-04-02 07:23 UTC
Labels: duplicate
